### ISSUE TITLE
Illegal character <j>

### ISSUE THREAD

**Issue by shuizhongyueming** [groenewege/vim-less#52]
I have just install the vim-less without any config.

But when I open a empty or not `.less` file.

it will alway show some error at the bottom, and disappear after a while.

and the plugin will work.

this is the error:

![image](https://cloud.githubusercontent.com/assets/2059860/8744842/10e5d7a8-2cad-11e5-9e78-9449fb231d0e.png)

and this is the code that has error in less.vim. But I dont know the syntax

    setlocal omnifunc=csscomplete#CompleteCSS
    setlocal suffixesadd=.less
    setlocal comments=sO:*\ -,mO:*\ \ ,exO:*/,://
    setlocal fo=jcroql  // this is where error happens

    let &l:include = '^\s*@import\s\+\%(url(\)\=["'']\='

My System is OSX 10.10.4
and the version of vim is: 7.3

**Comment by dhruvasagar** [comment]
Hi,

I just checked, apparently the option 'j' in formatoptions setting was introduced in 7.4 sometime, it's missing in 7.3. I would highly recommend upgrading vim.

However, besides that, you should be getting this error only when you open a less file / set filetype of a file to less, because that is when vim loads this plugin.

**Comment by shuizhongyueming** [comment]
thanks, I will try to upgrade my vim :)
